---

###debug:debug_ec2_facts.yml
#factsで取得したSGとサブネットの情報を表示する

#取得したセキュリティグループのIDを表示
- name: Show Security GroupID created now
  debug: var=ec2_group_facts.security_groups[0].group_id
    #var: "{{ ec2_group_facts.security_groups[0].group_id }}"


#取得したサブネットの、IDを表示
- name: Show SubnetID created now
  debug:
    msg:
     - "{{ item.subnets[0].id }}"
##with_itemsでループせずにする方法。直接変数を記入
#     - "{{ ec2_subnet_facts_pub.results[0].subnets[0].id}}"
#     - "{{ ec2_subnet_facts_pub.results[1].subnets[0].id}}"
  with_items: "{{ ec2_subnet_facts_pub.results }}"
