---

###2.ec2.yml
##EC2インスタンスを構築する。


#EC2インスタンスの構築(Public)
- name: Launch EC2 Instance created now
  ec2:
    key_name: "{{ aws.ec2.keypair }}"
    group_id: "{{ ec2_group_facts.security_groups[0].group_id }}"
    instance_type: "{{ aws.ec2.instance_type }}"
    instance_tags:
      Name: '{{ aws.ec2.instance_tags.Name }}'
    image: "{{ aws.ec2.image }}"
    wait: true
    region: "{{ aws.common.region }}"
    vpc_subnet_id: "{{ item.subnets[0].id }}"
#    vpc_subnet_id: "{{ ec2_subnet_facts_pub.results[0].subnets[0].id }}"
    count_tag: 
      Name: '{{ aws.ec2.instance_tags.Name }}'
    exact_count: "{{ aws.ec2.exact_count }}"
  with_items: "{{ ec2_subnet_facts_pub.results }}"
  register: ec2

