---
##使用するELBのサブネットの情報を収集
###

- name: "Gathering for VPC to stand on ELB "
  ec2_vpc_net_facts:
   region: "{{ aws.common.region }}" 
   filters:
      "tag:Name": "{{ aws.vpc.name }}"
  register: elb_target_vpc

- name: debug elb_target_subnets
  debug:
    msg:
      - "{{ elb_target_vpc.vpcs[0].vpc_id }}"


##使用するELBのサブネットの情報を収集
##

- name: "Gathering for ELB to stand on Subnets "
  ec2_vpc_subnet_facts:
    region: "{{ aws.common.region }}"
    filters:
      "tag:Name": "{{ item.value.tags.Name }}"
  with_dict: "{{ aws.vpc.subnet.pub }}"
  register: elb_target_subnets

- name: debug elb_target_subnets
  debug:
    msg:
      - "{{ elb_target_subnets.results[0].subnets[0].id }}"
      - "{{ elb_target_subnets.results[1].subnets[0].id }}"

#- name: set_fact elb_target_subnets.id
#  set_fact:
#    elb_subnet:
#     - "{{ item.subnets[0].id  }}"
#  with_items: "{{ elb_target_subnets.results }}"
#  register: set_fact_subnet
#
#- name: debug elb_target_subnets
#  debug:
#    msg:
#     - "{{ set_fact_subnet }}"

##使用するELBのセキュリティグループの情報を収集
##

- name: "Get Security Group ID"
  ec2_group_facts:
    region: "{{ aws.common.region }}"
    filters:
      group-name: "{{ aws.vpc.security_group.web.name }}"
  register: elb_target_sg

- name: "Show Security Group ID"
  debug: var=elb_target_sg.security_groups[0].group_id

##ターゲットグループとなるEC2の情報を収集
##

- name: "Gathering for elb to attache ec2"
  ec2_instance_facts:
    region: "{{ aws.common.region }}"
    filters:
      "tag:Name": Ansible EC2
  register: elb_target_ec2

- name: debug elb_target_ec2
  debug:
    msg:
     - "{{ item.instance_id  }}"
  with_items: "{{ elb_target_ec2.instances }}"
