---
###2:elb.yml
#ターゲットグループの作成、ELBの作成

##ターゲットグループの作成
##httpのみ
##phpMyAdminのステータスコードは300番台なので、300-400をhelthyとする。

- name: "Create Target Group for making to ELB"
  elb_target_group:
    name: "{{ aws.elb.target_group.name }}"
    region: "{{ aws.common.region }}"
    protocol: http
    port: 80
    vpc_id: "{{ elb_target_vpc.vpcs[0].vpc_id }}"
    health_check_path: /phpobiadmin
    successful_response_codes: "200,300-400"
    targets:
      - Id: "{{ elb_target_ec2.instances[0].instance_id }}"
        Port: 80
      - Id: "{{ elb_target_ec2.instances[1].instance_id }}"
        Port: 80
#      - Id: i-014bc5f357fa04631
#        Port: 80
#      - Id: i-044fc1638ee8cc760
#        Port: 80
    state: present
    wait_timeout: 200
    wait: True

##ELBを作成する
#種類はALB

- name: "Create ELB"
  elb_application_lb:
#  elb_network_lb:
    name: "{{ aws.elb.elb_name  }}"
    region: "{{ aws.common.region }}"
    security_groups: "{{ elb_target_sg.security_groups[0].group_id }}"
    subnets:
      - "{{ elb_target_subnets.results[0].subnets[0].id }}"
      - "{{ elb_target_subnets.results[1].subnets[0].id }}"
    listeners:
      - Protocol: HTTP
        Port: 80 # Required. The port on which the load balancer is listening.
        DefaultActions:
          - Type: forward # Required. Only 'forward' is accepted at this time
            TargetGroupName: "{{ aws.elb.target_group.name }}" # Required. The name of the target group
    state: present
    wait: yes
