---

###2:rds.yml
#サブネットグループの作成、RDSの作成

# RDSサブネットグループの作成
## rds_subnet_groupモジュールを使用
- name: "Make RDS Subnet Group"
  rds_subnet_group:
    state: present
    name: "{{ aws.rds.subnet_grp.name }}"
    description: My DB Subnet Group
    region: "{{ aws.common.region }}"
    subnets:
      - "{{ rds_subnet_fact.results[0].subnets[0].id }}"
      - "{{ rds_subnet_fact.results[1].subnets[0].id }}"
  register: rds_subnet_group_fact

- name: "Show RDS Subnet Group Name "
  debug: var=aws.rds.subnet_grp.name

# RDSの起動
## rdsモジュールを使用
- name: "Create RDS Instance"
  rds:
    command: create
    instance_name: "{{ aws.rds.rds_name }}"
    username: "{{ aws.rds.db_user }}"
    password: "{{ aws.rds.db_password }}"
    db_name: "{{ aws.rds.db_name }}"
    zone: "{{ aws.rds.aws_zone }}"
    subnet: "{{ aws.rds.subnet_grp.name }}"
    region: "{{ aws.common.region }}"
    vpc_security_groups: "{{ rds_sg_fact.security_groups[0].group_id }}"
    db_engine: MySQL
    instance_type: "{{ aws.rds.instance }}"
    size: "{{ aws.rds.size }}"
  register: rds_info_fact
  tags: rds

