---

###3:subnets.yml
#パブリックサブネットとプライベートサブネットを2つずつ作成する

- name: Public Subnet作成
  ec2_vpc_subnet:
    region: "{{ aws.common.region }}"
    state: present
    vpc_id: "{{ vpc_net.vpc.id }}"
    az: "{{ aws.common.region }}{{ item.value.zone }}"
    cidr: "{{ item.value.cidr }}"
    map_public: "{{ item.value.map_public|default(True) }}"
    tags: "{{ item.value.tags }}"
  with_dict: "{{ aws.vpc.subnet.pub }}"
  register: vpc_subnet_pub

- name: Private Subnet作成
  ec2_vpc_subnet:
    region: "{{ aws.common.region }}"
    state: present
    vpc_id: "{{ vpc_net.vpc.id }}"
    az: "{{ aws.common.region }}{{ item.value.zone }}"
    cidr: "{{ item.value.cidr }}"
    map_public: "{{ item.value.map_public|default(false) }}"
    tags: "{{ item.value.tags }}"
  with_dict: "{{ aws.vpc.subnet.pri }}"
  register: vpc_subnet_pri

