---

###1:vpc.yml
#vpcを作成する

- name: VPC作成
  ec2_vpc_net:
    name: "{{ aws.vpc.name }}"
    cidr_block: "{{ aws.vpc.cidr_block }}"
    region: "{{ aws.common.region }}"
    tags: "{{ aws.vpc.tags }}"
    tenancy: default
  register: vpc_net
