---
###3.apacheの変数ファイル

##PHP
#インストールするもの
php_pkgs:
  - php
  - php-mysql
  - php-mcrypt

#phpの設定ファイルのパス
php_dest: /etc/php.ini

#phpのタイムゾーンの設定
php_tz: '"Asia/Tokyo"'

##phpMyAdmin
#phpMyAdminの設定ファイル1のコピー元
#
#srcはtemplateモジュールからそのまま持ってくるので使用しない。
#phpmyadmin1_src: /roles/3.apache/files/phpMyAdmin.conf

#phpMyAdminの設定ファイル1のコピー先
phpmyadmin1_dest: /etc/httpd/conf.d/phpMyAdmin.conf

#phpMyAdminの設定ファイル1のコピー元
#phpmyadmin2_src: /roles/3.apache/files/config.inc.php

#phpMyAdminの設定ファイル2のコピー先
phpmyadmin2_dest: /etc/phpMyAdmin/config.inc.php

##AWSから情報を拾ってくるときに使うもの
#group_varsにもあるので使用しない。
#aws:
#  common:
#    region: ap-northeast-1
  
